server:
  port: 1234
spring:
  profiles:
    include: oauth2, db, jwt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  exclude:
    uri: /favicon.ico
--- # LOCAL
spring:
  config:
    activate:
      on-profile: local
file:
  save-path: C:/Users/sim/
  thumbnail:
    height: 250
    weight: 250

--- # DEV
spring:
  config:
    activate:
      on-profile: dev
file:
  save-path: C:/Users/sim/
  thumbnail:
    height: 250
    weight: 250

--- # PROD
spring:
  config:
    activate:
      on-profile: prod
file:
  save-path: C:/Users/sim/
  thumbnail:
    height: 250
    weight: 250
