server:
  port: 1234
spring:
  profiles:
    include: oauth2, db, jwt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

file:
  save-path: C:/Users/sim
  thumbnail:
    height: 250
    weight: 250

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

