spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: n9uvAXwAcy02qLC9U6Bp
            client-secret: ENC(H3J6MhMRMtTdcC/PMywAQDVg66fLzzhH)
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:1234/login/oauth2/code/naver
            client-authentication-method: client_secret_post
          kakao:
            client-id: 02ab99880d479ebc0b463f4402327e0b
            client-secret: ENC(rUCxDIfr63cAm2yV86Jj/7DKhY44zTNpxhI17e0C66aJKELs3BEKtbwgWBsx3dRA)
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:1234/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
          google:
            client-id: 184616621835-6lomb6cbp6vifd0sqb3s4fkp9ohbuqvo.apps.googleusercontent.com
            client-secret: ENC(5rW99FAyR/2MPMrnS7/7mKDQLSJFQZ+JD9c+Tu8KE8QQ5DXrui4Adg==)
            scope: profile, email
            client-name: google
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:1234/login/oauth2/code/google
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


