spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: ENC(lvfQePYKaLmO5GJpZglQEw==)
    password: ENC(HefilNAmTOBTUWXOtq0VsA==)
    url: ENC(JajA2IfRGX27gQzseW0mmVXORbkhKX1iu2p1wqYf7h+Zl8tCg1k2iIdyIBbUtQju)